spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pmt
    username: wael
    password: wael
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: wael
    password: wael
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  application:
    security:
      jwt:
        secret-key: DI3aKoVzJMbvAX7UQzdTRqqG7wxZg2wLZbaAyeJ8wF0=
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days

springdoc:
  default-produces-media-type: application/json

server:
  port: 8088